services:

  redis:
    image: redis
    container_name: redis

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgresql_db

  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

  celery:
    restart: always
    build: 
      context: .
    command: celery -A core worker -l DEBUG
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app